export const SWITCH_PLAYER = 'SWITCH_PLAYER'
export const MAKE_MOVE = 'MAKE_MOVE'
export const CHECK_OVERLAY_HINT = 'CHECK_OVERLAY_HINT'
export const REMOVE_HINT = 'REMOVE_HINT'
export const UNDO = 'UNDO'
export const RESET = 'RESET'
